apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals-app
  template:
    metadata:
      labels:
        app: animals-app
    spec:
      containers:
        - name: animals-app
          image: animals-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: animals-service
spec:
  selector:
    app: animals-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
